export enum SettingsType {
	LLM_MODEL = 'LLM_MODEL',
	TAG = 'TAG',
	SOURCE = 'SOURCE',
	RETRIEVAL_METHOD = 'RETRIEVAL_METHOD',
	RESPONSE_STYLE = 'RESPONSE_STYLE',
	RESPONSE_FORMAT = 'RESPONSE_FORMAT',
	AUTHORIZED_COMMANDS = 'AUTHORIZED_COMMANDS',
}
